### PR TITLE
Static method now returns cancelable promises too

### PR DESCRIPTION
**Pull request by HitoriSensei**

### CODE REVIEW

**Comment by birdy-** [comment]
It seems you kill the indent. Otherwise, why not implement it for all, but it's useless to create a cancelable promise for resolve or reject.

**Comment by HitoriSensei** [comment]
"it's useless to create a cancelable promise for resolve or reject."

That's not true if you use Promise.resolve to create a promise from a value
that can be both a plain computed value, but can also be a promise that is
not yet resolved, effectively enriching existing promise with cancellation
ability. In short, having ability to create cancellable promises using
static resolve/reject allows you to skip the parts when you have to check
if you are getting a promise or a value before turning it into a
cancellable promise.

Piotr "Hitori" Bosak

Software Architect
Hitori Studios
hitori.pl

02.06.2017 21:23 "Clément Danjou" <notifications@github.com> napisał(a):

It seems you kill the indent. Otherwise, why not implement it for all, but
it's useless to create a cancelable promise for resolve or reject.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/alkemics/CancelablePromise/pull/9#issuecomment-305886928>,
or mute the thread

**Comment by birdy-** [comment]
Ok I see. I'll try to update that.

**Comment by birdy-** [comment]
See #10

**Pull request closed without merging**
